version: "3.8"

services:
  db:
    container_name: postgres-football
    restart: always
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  redis:
    container_name: redis-football
    image: "redis:7"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # env_file: 
    #   - ./painel/.env
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  web:
    container_name: django-football
    build: .
    environment:
      - TZ=America/Sao_Paulo
    command: ["gunicorn", "-w", "20", "--bind", "0.0.0.0:8000", "--timeout", "86400", "aplicativo.wsgi:application"]
    working_dir: /code/painel
    restart: always
    volumes:
      - static:/code/painel/static
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  nginx:
    container_name: nginx-football
    restart: always
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  static:
  postgres_data: